#!/usr/bin/env python3
"""Fast docling server using DocumentConverter singleton.

A lightweight FastAPI server optimized for hybrid PDF processing:
1. Using a single DocumentConverter instance (no per-request initialization)
2. Returns only JSON (DoclingDocument format) - markdown/HTML generated by Java

Usage:
    opendataloader-pdf-hybrid [--port PORT] [--host HOST] [--ocr-lang LANG]
                              [--force-ocr | --no-ocr] [--ocr-engine ENGINE] [--psm N]
                              [--device DEVICE]
                              [--enrich-formula] [--enrich-picture-description]
                              [--max-file-size MB]

    # Default: http://localhost:5002
    opendataloader-pdf-hybrid

    # Custom port
    opendataloader-pdf-hybrid --port 5003

    # Disable OCR when the PDF already has reliable embedded text (#387)
    opendataloader-pdf-hybrid --no-ocr

    # Use Tesseract for a language EasyOCR doesn't support (#439)
    opendataloader-pdf-hybrid --ocr-engine tesseract --ocr-lang mal

    # Chinese + English OCR with force full-page OCR
    opendataloader-pdf-hybrid --ocr-lang "ch_sim,en" --force-ocr

    # Korean OCR
    opendataloader-pdf-hybrid --ocr-lang "ko"

    # Explicitly use Apple Silicon GPU (MPS)
    opendataloader-pdf-hybrid --device mps

    # Force CPU-only processing
    opendataloader-pdf-hybrid --device cpu

    # With formula enrichment (LaTeX extraction)
    opendataloader-pdf-hybrid --enrich-formula

    # With picture description (alt text generation)
    opendataloader-pdf-hybrid --enrich-picture-description

    # Combined: OCR + enrichments
    opendataloader-pdf-hybrid --ocr-lang "en" --enrich-formula --enrich-picture-description

API Endpoints:
    GET  /health              - Health check
    POST /v1/convert/file     - Convert PDF to JSON

The /v1/convert/file endpoint parameters:
    - files: PDF file (multipart/form-data)
    - page_ranges: Page range to process (optional)

Requirements:
    Install with hybrid extra: pip install opendataloader-pdf[hybrid]
"""

import argparse
import asyncio
import logging
import os
import re

from dotenv import load_dotenv
load_dotenv()
import sys
import tempfile
import threading
import time
import traceback

# Enable docling per-step pipeline profiling (layout, ocr, table_structure, etc.)
# Must be set before docling settings singleton is instantiated.
os.environ.setdefault("DOCLING_DEBUG_PROFILE_PIPELINE_TIMINGS", "true")
from contextlib import asynccontextmanager
from typing import Any, Optional

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# Configuration
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 5002
MAX_FILE_SIZE = 0  # No file size limit by default (0 = unlimited)
UPLOAD_CHUNK_SIZE = 1024 * 1024  # 1MB chunks for streaming upload

# OCR engine kinds we filter out from `--ocr-engine` choices.
# `kserve_v2_ocr` requires a separate KServe v2 / Triton inference server, which
# is unsuitable for the local hybrid mode this server is designed for.
# Single source of truth shared by `create_converter`, `main()` argparse, and tests
# to avoid drift between production and test code.
_OCR_ENGINE_DENYLIST = frozenset({"kserve_v2_ocr"})


def _non_negative_int(value: str) -> int:
    """Argparse type validator that rejects negative integers."""
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("--max-file-size must be >= 0")
    return parsed


# Global converter instance (initialized on startup with CLI options)
converter = None

# Serialize converter.convert() calls. The converter singleton was designed for
# sequential use; this lock keeps that guarantee while allowing the event loop
# to stay responsive via asyncio.to_thread().
_convert_lock = threading.Lock()

# Regex matching lone surrogates (U+D800..U+DFFF) and null characters
_INVALID_UNICODE_RE = re.compile(r"[\ud800-\udfff\x00]")


def _extract_failed_pages_from_errors(errors: list[str]) -> list[int]:
    """Extract failed page numbers from error messages.

    Docling error messages follow the pattern "Page N: <error>" (e.g.,
    "Page 26: std::bad_alloc") or, when no error description is available,
    a bare "Page N" with no colon. Even when docling includes failed pages
    in the pages dict as empty entries, the error messages reliably
    indicate which pages actually failed.

    Args:
        errors: List of error message strings.

    Returns:
        Sorted list of 1-indexed page numbers that failed.
    """
    failed = set()
    page_pattern = re.compile(r"^Page\s+(\d+)(?::|$)")
    for msg in errors:
        m = page_pattern.match(msg)
        if m:
            failed.add(int(m.group(1)))
    return sorted(failed)


def extract_timings(result: Any) -> dict[str, Any]:
    """Extract per-step pipeline timings from a Docling ConversionResult.

    Requires DOCLING_DEBUG_PROFILE_PIPELINE_TIMINGS=true (set at module level).
    Returns a dict keyed by step name (e.g. "layout", "ocr", "table_structure")
    with total_s, avg_s, and count for each step.
    """
    timings_out: dict[str, Any] = {}
    raw_timings = getattr(result, "timings", None)
    if not raw_timings:
        return timings_out
    for name, item in raw_timings.items():
        try:
            timings_out[name] = {
                "total_s": round(item.total(), 4),
                "avg_s": round(item.avg(), 4) if item.count > 0 else 0.0,
                "count": item.count,
            }
        except Exception:
            # Gracefully skip if ProfilingItem API changes
            pass
    return timings_out


def build_conversion_response(
    status_value: str,
    json_content: dict,
    processing_time: float,
    errors: list[str],
    requested_pages: tuple[int, int] | None,
    total_pages: int | None = None,
    timings: dict[str, Any] | None = None,
) -> dict:
    """Build a structured conversion response with status and failed page info.

    When Docling encounters errors (e.g., std::bad_alloc in PDF preprocessing),
    it may still include failed pages as empty entries in the pages dict.
    This function combines two strategies to detect failed pages:
    1. Parse page numbers from error messages ("Page N: <error>")
    2. Detect pages missing from the output pages dict (gap detection)
    Both results are merged (union) since each catches a different failure mode.

    Args:
        status_value: Docling ConversionStatus value as string (e.g., "success", "partial_success").
        json_content: The exported document dict from Docling.
        processing_time: Time taken for conversion in seconds.
        errors: List of error message strings from Docling.
        requested_pages: Tuple of (start, end) 1-indexed page range, or None for all pages.
        total_pages: Total page count of the input document (from Docling InputDocument).
                     Used to detect boundary page failures when requested_pages is None.

    Returns:
        Response dict with status, document, errors, failed_pages, and processing_time.
    """
    failed_pages: list[int] = []

    if status_value == "partial_success":
        # Strategy 1: Extract failed pages from error messages (reliable —
        # docling may include failed pages as empty entries in the pages dict,
        # making gap detection ineffective)
        error_failed = set(_extract_failed_pages_from_errors(errors))

        # Strategy 2: Detect pages missing from the pages dict (catches
        # failures that don't produce "Page N:" error messages)
        gap_failed: set[int] = set()
        pages_dict = json_content.get("pages", {})
        present_pages = set()
        for k in pages_dict.keys():
            try:
                present_pages.add(int(k))
            except (ValueError, TypeError):
                logger.warning("Unexpected non-integer page key in Docling output: %r", k)

        if requested_pages:
            expected_pages = set(range(requested_pages[0], requested_pages[1] + 1))
        elif total_pages is not None:
            expected_pages = set(range(1, total_pages + 1))
        elif present_pages:
            logger.warning(
                "No page range or total_pages available; boundary page failures cannot be detected"
            )
            expected_pages = set(range(min(present_pages), max(present_pages) + 1))
        else:
            expected_pages = set()

        gap_failed = expected_pages - present_pages

        # Union: each strategy catches a different failure mode
        failed_pages = sorted(error_failed | gap_failed)

    response: dict[str, Any] = {
        "status": status_value,
        "document": {
            "json_content": json_content,
        },
        "processing_time": processing_time,
        "errors": errors,
        "failed_pages": failed_pages,
    }

    if timings:
        response["timings"] = timings

    return response


def sanitize_unicode(data: Any) -> Any:
    """Recursively replace lone surrogates and null characters with U+FFFD.

    Docling OCR can produce lone surrogates (U+D800-U+DFFF) and null characters
    from PDFs with malformed font encodings. These pass through json.dumps(ensure_ascii=False)
    but fail on .encode('utf-8') in Starlette's JSONResponse.render(), causing
    UnicodeEncodeError and a 500 response.

    This mirrors the Java-side TextProcessor.replaceUndefinedCharacters().

    Args:
        data: Arbitrary data structure (dict, list, str, or primitive) from
              Docling's export_to_dict() output.

    Returns:
        The same structure with problematic characters replaced by U+FFFD.
    """
    if isinstance(data, str):
        return _INVALID_UNICODE_RE.sub("\ufffd", data)
    if isinstance(data, dict):
        return {k: sanitize_unicode(v) for k, v in data.items()}
    if isinstance(data, list):
        return [sanitize_unicode(item) for item in data]
    return data


def _get_loop_setting() -> str:
    """Return the uvicorn event loop setting appropriate for the current platform.

    uvloop is not supported on Windows, so we force 'asyncio' there.
    On other platforms, 'auto' lets uvicorn use uvloop if available.
    """
    if sys.platform == "win32":
        return "asyncio"
    return "auto"


def _check_dependencies():
    """Check if hybrid dependencies are installed."""
    missing = []
    try:
        import uvicorn  # noqa: F401
    except ImportError:
        missing.append("uvicorn")
    try:
        import fastapi  # noqa: F401
    except ImportError:
        missing.append("fastapi")
    try:
        import docling  # noqa: F401
    except ImportError:
        missing.append("docling")

    if missing:
        raise ImportError(
            f"Missing dependencies: {', '.join(missing)}. "
            "Install with: pip install opendataloader-pdf[hybrid]"
        )


def _check_ocr_engine_available(engine_kind: str) -> tuple[bool, str]:
    """Probe runtime prerequisites for the selected OCR engine.

    Called at startup so a missing binary or Python package surfaces before the
    first request rather than mid-conversion. Returns (ok, error_message).

    `easyocr` ships with the `[hybrid]` extra and `auto` defers engine choice to
    docling at conversion time, so both are treated as always available. Other
    engines pull in extra system or Python dependencies that are not declared
    in pyproject and must be installed by the user.
    """
    import importlib.util
    import shutil

    if engine_kind in ("auto", "easyocr"):
        return True, ""

    if engine_kind == "tesseract":
        # docling's TesseractCliOcrOptions shells out to the `tesseract` binary.
        if shutil.which("tesseract") is None:
            return False, (
                "OCR engine 'tesseract' selected but the `tesseract` binary was not "
                "found on PATH. Install Tesseract for your platform "
                "(e.g., `brew install tesseract`, `apt install tesseract-ocr`, "
                "`choco install tesseract`) and ensure the language data files for "
                "your --ocr-lang are installed (e.g., `tesseract-ocr-mal` for Malayalam)."
            )
        return True, ""

    if engine_kind == "tesserocr":
        if importlib.util.find_spec("tesserocr") is None:
            return False, (
                "OCR engine 'tesserocr' selected but the `tesserocr` Python package "
                "is not installed. Install it with `pip install tesserocr` "
                "(libtesseract must also be available at runtime; on Windows install "
                "a wheel that matches your installed Tesseract major version)."
            )
        return True, ""

    if engine_kind == "rapidocr":
        # rapidocr's default backend is ONNX Runtime; docling 2.91 imports
        # `from rapidocr import EngineType, RapidOCR` and routes through it.
        if importlib.util.find_spec("rapidocr") is None:
            return False, (
                "OCR engine 'rapidocr' selected but the `rapidocr` Python package "
                "is not installed. Install it with `pip install rapidocr onnxruntime`."
            )
        if importlib.util.find_spec("onnxruntime") is None:
            return False, (
                "OCR engine 'rapidocr' selected but `onnxruntime` is not installed. "
                "rapidocr's default backend requires it. Install with "
                "`pip install onnxruntime` (or, for GPU, `pip install onnxruntime-gpu`)."
            )
        return True, ""

    if engine_kind == "ocrmac":
        if sys.platform != "darwin":
            return False, (
                "OCR engine 'ocrmac' selected but this is not macOS "
                f"(platform={sys.platform!r}). The ocrmac engine uses Apple's Vision "
                "framework and only runs on macOS."
            )
        if importlib.util.find_spec("ocrmac") is None:
            return False, (
                "OCR engine 'ocrmac' selected but the `ocrmac` Python package "
                "is not installed. Install it with `pip install ocrmac`."
            )
        return True, ""

    # Unknown engine kind — fail closed. argparse `choices` filters the CLI
    # surface, so this branch is reachable via direct programmatic calls or
    # when docling registers a new engine kind we haven't added a probe for.
    # Falling through to True would silently green-light unverified engines
    # and defer the failure to the first conversion request.
    return False, (
        f"OCR engine {engine_kind!r} is not recognized by the availability "
        "probe. Add a probe branch for this engine kind in "
        "`_check_ocr_engine_available()`."
    )


def create_converter(
    force_full_page_ocr: bool = False,
    disable_ocr: bool = False,
    ocr_engine: str = "easyocr",
    psm: int | None = None,
    ocr_lang: list[str] | None = None,
    enrich_formula: bool = False,
    enrich_picture_description: bool = False,
    picture_description_prompt: str | None = None,
    device: str = "auto",
):
    """Create a DocumentConverter with the specified options.

    Args:
        force_full_page_ocr: If True, force OCR on all pages regardless of text content.
                            If False (default), OCR only where needed.
        disable_ocr: If True, disable OCR entirely (do_ocr=False). Useful when input PDFs
                    already have reliable embedded text — prevents duplicate text extraction
                    from images (charts, diagrams, screenshots). Mutually exclusive with
                    force_full_page_ocr at the CLI level.
        ocr_engine: OCR engine kind to use. Engine availability is delegated to docling's
                    factory (`get_ocr_factory`). Each engine has its own license, language
                    coverage, and accuracy characteristics; this project does not validate
                    engine accuracy. Default: "easyocr" (preserves prior behavior).
        psm: Tesseract Page Segmentation Mode. Only applied when ocr_engine is
             "tesseract" or "tesserocr". Ignored otherwise. Range and semantics
             are owned by Tesseract / docling; see `tesseract --help-extra`.
        ocr_lang: List of OCR language codes. The code system depends on the chosen engine
                  (EasyOCR uses 'ko,en', Tesseract uses 'kor,eng', RapidOCR uses
                  'english,chinese', ocrmac uses 'en-US'). If None, the engine's default
                  languages are used.
        enrich_formula: If True, enable formula enrichment (LaTeX extraction).
        enrich_picture_description: If True, enable picture description (alt text generation).
        picture_description_prompt: Custom prompt forwarded to the VLM. If None or blank/whitespace-only, docling's default prompt is used.
        device: Accelerator device for model inference. Options: "auto", "cpu", "cuda", "mps", "xpu".
                "auto" lets Docling select the best available device. Default: "auto".
    """
    from docling.datamodel.accelerator_options import AcceleratorOptions
    from docling.datamodel.base_models import InputFormat
    from docling.datamodel.pipeline_options import (
        AcceleratorOptions,
        PdfPipelineOptions,
        PictureDescriptionVlmOptions,
        TableFormerMode,
        TableStructureOptions,
        TesseractCliOcrOptions,
        TesseractOcrOptions,
    )
    from docling.document_converter import DocumentConverter, PdfFormatOption
    from docling.models.factories import get_ocr_factory

    # Delegate engine selection to docling's factory. We block external plugins for
    # security/reproducibility; the module-level _OCR_ENGINE_DENYLIST filters
    # engines unsuitable for hybrid local mode (e.g., remote inference servers).
    ocr_factory = get_ocr_factory(allow_external_plugins=False)
    if ocr_engine in _OCR_ENGINE_DENYLIST:
        # Programmatic callers (importing this module) bypass argparse `choices`,
        # so enforce the denylist here too. Without this, the module-level claim
        # that `_OCR_ENGINE_DENYLIST` is shared across CLI and create_converter
        # would only be true at the CLI layer.
        available = sorted(set(ocr_factory.registered_kind) - _OCR_ENGINE_DENYLIST)
        raise ValueError(
            f"OCR engine '{ocr_engine}' is not supported in hybrid local mode "
            f"(filtered by _OCR_ENGINE_DENYLIST). Available engines: {available}"
        )
    try:
        ocr_options = ocr_factory.create_options(
            kind=ocr_engine,
            force_full_page_ocr=force_full_page_ocr,
        )
    except RuntimeError as e:
        # Library-friendly error type so programmatic callers can catch and retry
        # with a different engine. main() relies on argparse `choices` to gate
        # invalid CLI input, so this branch is reached only via direct calls.
        available = sorted(set(ocr_factory.registered_kind) - _OCR_ENGINE_DENYLIST)
        raise ValueError(
            f"Unknown ocr_engine '{ocr_engine}': {e}\nAvailable engines: {available}"
        ) from e

    if ocr_lang:
        ocr_options.lang = ocr_lang

    # Tesseract-only: Page Segmentation Mode
    if psm is not None and isinstance(
        ocr_options, (TesseractOcrOptions, TesseractCliOcrOptions)
    ):
        ocr_options.psm = psm

    # Configure picture description options with custom prompt.
    # When picture_description_prompt is None or blank, omit the field so
    # docling's built-in default prompt is used. A blank string would otherwise
    # silently produce empty-prompt output — same class of silent-flag bug
    # as PDFDLOSP-20 reported.
    picture_description_options = None
    if enrich_picture_description:
        vlm_kwargs: dict[str, Any] = {
            "repo_id": "HuggingFaceTB/SmolVLM-256M-Instruct",
        }
        if picture_description_prompt and picture_description_prompt.strip():
            vlm_kwargs["prompt"] = picture_description_prompt
        picture_description_options = PictureDescriptionVlmOptions(**vlm_kwargs)

    pipeline_kwargs = {
        "do_ocr": not disable_ocr,
        "do_table_structure": True,
        "ocr_options": ocr_options,
        "table_structure_options": TableStructureOptions(mode=TableFormerMode.ACCURATE),
        "do_formula_enrichment": enrich_formula,
        "do_picture_description": enrich_picture_description,
        "generate_picture_images": enrich_picture_description,
        "accelerator_options": AcceleratorOptions(device=device),
    }
    if picture_description_options is not None:
        pipeline_kwargs["picture_description_options"] = picture_description_options

    if device != "auto":
        pipeline_kwargs["accelerator_options"] = AcceleratorOptions(device=device)

    pipeline_options = PdfPipelineOptions(**pipeline_kwargs)

    return DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
        }
    )


def create_app(
    force_ocr: bool = False,
    disable_ocr: bool = False,
    ocr_engine: str = "easyocr",
    psm: int | None = None,
    ocr_lang: list[str] | None = None,
    enrich_formula: bool = False,
    enrich_picture_description: bool = False,
    picture_description_prompt: str | None = None,
    max_file_size: int = MAX_FILE_SIZE,
    device: str = "auto",
    use_gemini_agent: bool = False,
    gemini_model: str = "gemini-2.0-flash",
):
    """Create and configure the FastAPI application.

    Args:
        force_ocr: If True, force full-page OCR on all pages.
        disable_ocr: If True, disable OCR entirely. Mutually exclusive with force_ocr at CLI.
        ocr_engine: OCR engine kind (delegated to docling's get_ocr_factory). Default: "easyocr".
        psm: Tesseract Page Segmentation Mode. Only applied for Tesseract engines.
        ocr_lang: List of OCR language codes (engine-specific format).
        enrich_formula: If True, enable formula enrichment (LaTeX extraction).
        enrich_picture_description: If True, enable picture description (alt text generation).
        picture_description_prompt: Custom prompt forwarded to the VLM. If None or blank/whitespace-only, docling's default prompt is used.
        max_file_size: Maximum file size in bytes. 0 means no limit (default).
        device: Accelerator device for model inference ("auto", "cpu", "cuda", "mps", "xpu").
        use_gemini_agent: Use Gemini multimodal agent for visual tagging.
        gemini_model: Gemini model name for the agent.
    """
    from fastapi import FastAPI, File, Form, UploadFile, Request, BackgroundTasks
    from fastapi.responses import JSONResponse, StreamingResponse, HTMLResponse, FileResponse
    from pathlib import Path
    import uuid
    import subprocess
    import sys

    # Profile converters: initialized lazily on first /v1/profile/file request
    profile_converters: dict[str, Any] = {}

    _docling_converter = None
    _gemini_converter = None
    _converter_lock = threading.Lock()

    def get_docling_converter():
        nonlocal _docling_converter
        global converter
        with _converter_lock:
            if converter is not None:
                _docling_converter = converter
                return _docling_converter
            if _docling_converter is None:
                logger.info("Initializing Docling DocumentConverter...")
                _docling_converter = create_converter(
                    force_full_page_ocr=force_ocr,
                    disable_ocr=disable_ocr,
                    ocr_engine=ocr_engine,
                    psm=psm,
                    ocr_lang=ocr_lang,
                    enrich_formula=enrich_formula,
                    enrich_picture_description=enrich_picture_description,
                    picture_description_prompt=picture_description_prompt,
                    device=device,
                )
            return _docling_converter

    def get_gemini_converter():
        nonlocal _gemini_converter
        with _converter_lock:
            if _gemini_converter is None:
                logger.info(f"Initializing GeminiAgentConverter (model={gemini_model})...")
                from .agent import GeminiAgentConverter
                _gemini_converter = GeminiAgentConverter(model_name=gemini_model)
            return _gemini_converter

    @asynccontextmanager
    async def lifespan(_app: FastAPI):
        """Lifespan context manager for startup and shutdown events."""
        global converter
        start = time.perf_counter()
        if use_gemini_agent:
            converter = get_gemini_converter()
        else:
            converter = get_docling_converter()
        elapsed = time.perf_counter() - start
        logger.info(f"Converter pre-initialized in {elapsed:.2f}s")
        yield

    app = FastAPI(
        title="Docling Fast Server",
        description="Fast PDF conversion using docling SDK with singleton pattern",
        version="1.0.0",
        lifespan=lifespan,
    )

    # In-memory storage for web agent tagging tasks
    tasks: dict[str, dict] = {}
    WEB_WORK_DIR = Path(tempfile.gettempdir()) / "opendataloader_web"

    async def _process_conversion(converter_instance, files: UploadFile, page_ranges: Optional[str]):
        if converter_instance is None:
            return JSONResponse(
                {"status": "failure", "errors": ["Converter not initialized"]},
                status_code=503,
            )

        # Parse page_ranges string to tuple
        page_range_tuple = None
        if page_ranges:
            try:
                parts = page_ranges.split("-")
                if len(parts) == 2:
                    page_range_tuple = (int(parts[0]), int(parts[1]))
            except ValueError:
                pass

        # Stream upload to temp file and enforce size incrementally
        tmp_path = None
        total_size = 0
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp_path = tmp.name
            while True:
                chunk = await files.read(UPLOAD_CHUNK_SIZE)
                if not chunk:
                    break
                total_size += len(chunk)
                if max_file_size > 0 and total_size > max_file_size:
                    tmp.close()
                    os.unlink(tmp_path)
                    return JSONResponse(
                        {
                            "status": "failure",
                            "errors": [f"File size exceeds maximum allowed ({max_file_size // (1024*1024)}MB)"],
                        },
                        status_code=413,
                    )
                tmp.write(chunk)

        try:
            def _do_convert():
                with _convert_lock:
                    t0 = time.perf_counter()
                    if page_range_tuple:
                        res = converter_instance.convert(tmp_path, page_range=page_range_tuple)
                    else:
                        res = converter_instance.convert(tmp_path)
                    return res, time.perf_counter() - t0

            result, processing_time = await asyncio.to_thread(_do_convert)

            # Export to JSON (DoclingDocument format)
            json_content = result.document.export_to_dict()

            # Sanitize lone surrogates and null chars from OCR output to prevent
            # UnicodeEncodeError in Starlette's JSONResponse.render()
            json_content = sanitize_unicode(json_content)

            # Extract status and errors from Docling ConversionResult
            from docling.datamodel.base_models import ConversionStatus

            status_value = result.status.value if hasattr(result.status, "value") else str(result.status)
            errors = [getattr(e, "error_message", str(e)) for e in result.errors] if result.errors else []

            # Get total page count for accurate failed-page detection
            input_page_count = getattr(result.input, "page_count", None) if result.input else None

            if result.status == ConversionStatus.PARTIAL_SUCCESS:
                logger.warning(
                    "Docling returned partial_success: %d error(s), failed_pages will be reported",
                    len(errors),
                )

            # Extract per-step pipeline timings (layout, ocr, table_structure, etc.)
            step_timings = extract_timings(result)

            response = build_conversion_response(
                status_value=status_value,
                json_content=json_content,
                processing_time=processing_time,
                errors=errors,
                requested_pages=page_range_tuple,
                total_pages=input_page_count,
                timings=step_timings,
            )

            return JSONResponse(response)

        except Exception as e:
            logger.error(f"PDF conversion failed: {e}\n{traceback.format_exc()}")
            return JSONResponse(
                {
                    "status": "failure",
                    "errors": ["PDF conversion failed. Check server logs for details."],
                },
                status_code=500,
            )
        finally:
            if tmp_path and os.path.exists(tmp_path):
                os.unlink(tmp_path)

    # Web UI Routes
    @app.get("/", response_class=HTMLResponse)
    async def get_index():
        from .web_ui import HTML_CONTENT
        return HTMLResponse(content=HTML_CONTENT)

    @app.get("/v1/agent/config")
    async def get_config():
        return {
            "default_model": gemini_model,
            "default_workers": 1,
            "has_key": bool(os.environ.get("GEMINI_API_KEY")),
            "current_mode_agent": use_gemini_agent
        }

    def run_tagging_task_thread(
        task_id: str,
        input_path: str,
        engine: str,
        model: str,
        workers: int,
        page_ranges: Optional[str],
        host_url: str,
        custom_api_key: Optional[str],
        language: Optional[str] = None,
        title: Optional[str] = None,
        enrich_picture_description: bool = False
    ):
        try:
            tasks[task_id]["status"] = "running"
            tasks[task_id]["progress"] = 10
            tasks[task_id]["logs"].append(f"INFO - Starting PDF Tagging Pipeline with engine: {engine}")

            web_work_dir = Path(tempfile.gettempdir()) / "opendataloader_web"
            web_work_dir.mkdir(parents=True, exist_ok=True)
            input_stem = Path(input_path).stem

            if engine == "gemini":
                tasks[task_id]["logs"].append("INFO - Initializing Gemini Multimodal Agent...")
                tasks[task_id]["progress"] = 15

                # 1. Run Gemini converter to audit layout and write form fields
                from opendataloader_pdf.agent import GeminiAgentConverter
                converter_instance = GeminiAgentConverter(
                    api_key=custom_api_key,
                    model_name=model,
                    max_workers=workers,
                    should_cancel=lambda: tasks[task_id].get("cancel", False),
                )

                page_range_tuple = None
                if page_ranges:
                    try:
                        parts = page_ranges.split("-")
                        if len(parts) == 2:
                            page_range_tuple = (int(parts[0]), int(parts[1]))
                    except Exception:
                        pass

                tasks[task_id]["logs"].append("INFO - Analyzing visual layout and tagging form fields (Gemini)...")
                tasks[task_id]["progress"] = 25

                import logging
                agent_logger = logging.getLogger("pdf_tagger_agent")

                class TaskLogHandler(logging.Handler):
                    def emit(self, record):
                        log_msg = self.format(record)
                        tasks[task_id]["logs"].append(log_msg)

                handler = TaskLogHandler()
                handler.setFormatter(logging.Formatter("%(levelname)s - %(message)s"))
                agent_logger.addHandler(handler)

                def progress_cb(completed, total):
                    if tasks[task_id]["cancel"]:
                        raise RuntimeError("User cancelled the task")
                    page_progress = 25 + int((completed / total) * 43)
                    tasks[task_id]["progress"] = page_progress
                    tasks[task_id]["logs"].append(f"INFO - Page progress: {completed} of {total} completed.")

                try:
                    result = converter_instance.convert(input_path, page_range=page_range_tuple, progress_callback=progress_cb)
                finally:
                    agent_logger.removeHandler(handler)

                if result.status == "failure":
                    errors_str = ", ".join(result.errors)
                    raise Exception(f"Visual layout analysis failed: {errors_str}")

                temp_pdf_path = getattr(converter_instance, "temp_pdf_path", None)
                if not temp_pdf_path or not os.path.exists(temp_pdf_path):
                    raise Exception("Failed to generate modified PDF with updated form fields.")

                tasks[task_id]["layout_json"] = result.document.export_to_dict()
                tasks[task_id]["progress"] = 70
                tasks[task_id]["logs"].append("INFO - Invoking Java tagging engine to compile accessibility tags into PDF...")

                hybrid_url = f"{host_url}/v1/agent/callback/{task_id}"

                cmd = [
                    sys.executable,
                    "-m",
                    "opendataloader_pdf.wrapper",
                    temp_pdf_path,
                    "--format", "tagged-pdf",
                    "--output-dir", str(web_work_dir),
                    "--hybrid", "docling-fast",
                    "--hybrid-mode", "full",
                    "--hybrid-url", hybrid_url,
                ]
            else:
                tasks[task_id]["logs"].append("INFO - Running Docling Fast Layout Engine...")
                tasks[task_id]["progress"] = 25
                hybrid_url = f"{host_url}/docling"

                cmd = [
                    sys.executable,
                    "-m",
                    "opendataloader_pdf.wrapper",
                    input_path,
                    "--format", "tagged-pdf",
                    "--output-dir", str(web_work_dir),
                    "--hybrid", "docling-fast",
                    "--hybrid-mode", "full",
                    "--hybrid-url", hybrid_url,
                ]
                if page_ranges:
                    cmd.extend(["--pages", page_ranges])
                
                if enrich_picture_description:
                    hybrid_url = f"{host_url}/docling/picture"
                    cmd[cmd.index("--hybrid-url") + 1] = hybrid_url

            tasks[task_id]["logs"].append(f"INFO - Executing subprocess: {' '.join(cmd)}")

            # Check for cancellation before starting subprocess
            if tasks[task_id]["cancel"]:
                tasks[task_id]["logs"].append("[CANCELLED] Task cancelled before Java subprocess")
                tasks[task_id]["status"] = "cancelled"
                return

            sub_env = os.environ.copy()
            if custom_api_key:
                sub_env["GEMINI_API_KEY"] = custom_api_key
            # Pass document language and title to Java via environment variables
            # These are used by AutoTaggingProcessor to set PDF/UA metadata
            if language and language.strip():
                sub_env["ODL_PDF_LANG"] = language.strip()
            if title and title.strip():
                sub_env["ODL_PDF_TITLE"] = title.strip()

            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
                env=sub_env
            )

            while True:
                line = process.stdout.readline()
                if not line and process.poll() is not None:
                    break
                if line:
                    line_str = line.strip()
                    tasks[task_id]["logs"].append(line_str)
                    if "Compiling PDF/UA structure tree" in line_str or "Parsing layout" in line_str:
                        tasks[task_id]["progress"] = 85
                    elif "Successfully generated tagged PDF" in line_str:
                        tasks[task_id]["progress"] = 95
                
                # Check for cancellation during subprocess
                if tasks[task_id]["cancel"]:
                    process.terminate()
                    try:
                        process.wait(timeout=5)
                    except subprocess.TimeoutExpired:
                        process.kill()
                    tasks[task_id]["logs"].append("[CANCELLED] Task cancelled during Java subprocess")
                    tasks[task_id]["status"] = "cancelled"
                    return

            return_code = process.wait()

            if engine == "gemini" and temp_pdf_path and os.path.exists(temp_pdf_path):
                try:
                    os.unlink(temp_pdf_path)
                except Exception:
                    pass

            if return_code == 0:
                if engine == "gemini":
                    temp_stem = Path(temp_pdf_path).stem
                    generated_output = web_work_dir / f"{temp_stem}_tagged.pdf"
                else:
                    generated_output = web_work_dir / f"{input_stem}_tagged.pdf"

                final_output = web_work_dir / f"{input_stem}_tagged.pdf"

                if generated_output.exists():
                    if generated_output != final_output:
                        if final_output.exists():
                            final_output.unlink()
                        generated_output.rename(final_output)
                    tasks[task_id]["status"] = "completed"
                    tasks[task_id]["progress"] = 100
                    tasks[task_id]["output_file"] = str(final_output)
                    tasks[task_id]["logs"].append("SUCCESS - PDF tagging completed successfully. Ready for download.")
                else:
                    raise Exception(f"Output tagged PDF file not found at {generated_output}.")
            else:
                raise Exception(f"Tagging process exited with code {return_code}")

        except Exception as e:
            tasks[task_id]["status"] = "failed"
            tasks[task_id]["error"] = str(e)
            tasks[task_id]["logs"].append(f"ERROR - Tagging failed: {str(e)}")
            logger.error(f"Task {task_id} failed: {e}", exc_info=True)
        finally:
            if input_path and os.path.exists(input_path):
                try:
                    os.unlink(input_path)
                except Exception:
                    pass

    @app.post("/v1/agent/tag")
    async def tag_pdf(
        background_tasks: BackgroundTasks,
        request: Request,
        file: UploadFile = File(...),
        engine: str = Form("gemini"),
        model: str = Form("gemini-2.0-flash"),
        pages: Optional[str] = Form(default=None),
        page_ranges: Optional[str] = Form(default=None),
        api_key: Optional[str] = Form(default=None),
        custom_api_key: Optional[str] = Form(default=None),
        workers: Optional[str] = Form(default=None),
        language: Optional[str] = Form(default=None),
        title: Optional[str] = Form(default=None),
        enrich_picture_description: Optional[str] = Form(default=None)
    ):
        effective_pages = page_ranges if page_ranges else pages
        effective_api_key = custom_api_key if custom_api_key else api_key
        try:
            effective_workers = int(workers) if workers else 3
        except ValueError:
            effective_workers = 3
        # Keep workers in a safe range to avoid overloading Gemini or local CPU.
        effective_workers = max(1, min(effective_workers, 12))

        task_id = f"tag_{uuid.uuid4().hex[:8]}"
        web_work_dir = Path(tempfile.gettempdir()) / "opendataloader_web"
        web_work_dir.mkdir(parents=True, exist_ok=True)
        
        input_path = web_work_dir / f"{task_id}_input.pdf"
        
        # Stream file to disk
        with open(input_path, "wb") as f:
            while True:
                chunk = await file.read(UPLOAD_CHUNK_SIZE)
                if not chunk:
                    break
                f.write(chunk)
                
        # Initialize task info
        tasks[task_id] = {
            "status": "pending",
            "progress": 0,
            "logs": [],
            "error": None,
            "output_file": None,
            "layout_json": None,
            "original_filename": file.filename,
            "cancel": False
        }
        
        # Get base URL of current server (e.g. http://127.0.0.1:5002)
        base_url = str(request.base_url).rstrip('/')
        
        # If the host is 0.0.0.0, replace it with 127.0.0.1 for local callback
        if "0.0.0.0" in base_url:
            base_url = base_url.replace("0.0.0.0", "127.0.0.1")
            
        # Run tagging in the background
        background_tasks.add_task(
            run_tagging_task_thread,
            task_id=task_id,
            input_path=str(input_path),
            engine=engine,
            model=model,
            workers=effective_workers,
            page_ranges=effective_pages,
            host_url=base_url,
            custom_api_key=effective_api_key,
            language=language,
            title=title,
            enrich_picture_description=(enrich_picture_description == "true")
        )
        
        return {"task_id": task_id, "status": "pending"}

    @app.get("/v1/agent/tasks/{task_id}/status")
    async def get_task_status(task_id: str, since: int = 0):
        if task_id not in tasks:
            return JSONResponse({"detail": "Task not found"}, status_code=404)
            
        task = tasks[task_id]
        logs = task["logs"][since:]
        
        return {
            "status": task["status"],
            "progress": task["progress"],
            "logs": logs,
            "error": task["error"],
            "output_url": f"/v1/agent/tasks/{task_id}/download" if task["status"] == "completed" else None
        }

    @app.post("/v1/agent/tasks/{task_id}/cancel")
    async def cancel_task(task_id: str):
        if task_id not in tasks:
            return JSONResponse({"detail": "Task not found"}, status_code=404)
        
        task = tasks[task_id]
        if task["status"] == "completed":
            return JSONResponse({"detail": "Task already completed"}, status_code=400)
        
        # Mark task for cancellation
        tasks[task_id]["cancel"] = True
        tasks[task_id]["status"] = "cancelled"
        tasks[task_id]["logs"].append("[CANCELLED] User requested task cancellation")
        
        return {"status": "cancelled", "task_id": task_id}

    @app.get("/v1/agent/tasks/{task_id}/download")
    async def download_task_output(task_id: str):
        if task_id not in tasks:
            return JSONResponse({"detail": "Task not found"}, status_code=404)
            
        task = tasks[task_id]
        if task["status"] != "completed" or not task["output_file"]:
            return JSONResponse({"detail": "Task not completed or file not found"}, status_code=400)
            
        output_path = Path(task["output_file"])
        if not output_path.exists():
            return JSONResponse({"detail": "File not found on disk"}, status_code=404)
            
        original_name = task.get("original_filename", "document.pdf")
        download_name = original_name.replace(".pdf", "_tagged.pdf") if original_name.endswith(".pdf") else f"{original_name}_tagged.pdf"

        return FileResponse(
            path=output_path,
            filename=download_name,
            media_type="application/pdf"
        )

    @app.get("/v1/agent/callback/{task_id}/health")
    async def callback_health(task_id: str):
        if task_id not in tasks:
            return JSONResponse({"status": "failure", "errors": ["Task not found"]}, status_code=404)
        return {"status": "ok"}

    @app.post("/v1/agent/callback/{task_id}/v1/convert/file")
    async def agent_callback(task_id: str):
        if task_id not in tasks:
            return JSONResponse({"status": "failure", "errors": ["Task not found"]}, status_code=404)
            
        layout_json = tasks[task_id].get("layout_json")
        if not layout_json:
            return JSONResponse({"status": "failure", "errors": ["Layout JSON not ready"]}, status_code=400)
            
        return JSONResponse({
            "status": "success",
            "document": {"json_content": layout_json},
            "errors": [],
            "failed_pages": []
        })

    @app.post("/v1/agent/deduplicate-fields")
    async def deduplicate_fields(fields_data: dict):
        """Standalone endpoint to deduplicate and enrich form fields.
        
        Expected input:
        {
            "form_fields": [
                {
                    "page_no": 1,
                    "name": "email",
                    "type": "text",
                    "bbox": [0, 0, 10, 10],
                    "tooltip": "Email address"
                }
            ]
        }
        
        Returns deduplicated, split, and enriched fields.
        """
        try:
            form_fields = fields_data.get("form_fields", [])
            if not form_fields:
                return JSONResponse({"detail": "No form fields provided"}, status_code=400)
            
            # Ensure each field has required fields
            for field in form_fields:
                field.setdefault("page_no", 1)
                field.setdefault("type", "text")
                field.setdefault("bbox", [0, 0, 10, 10])
                field.setdefault("tooltip", "")
                field.setdefault("original_name", field.get("name", ""))
                field.setdefault("original_tooltip", field.get("tooltip", ""))
                field.setdefault("nearby_text", [])
            
            # Create a minimal converter instance for processing
            from opendataloader_pdf.agent import GeminiAgentConverter
            converter = GeminiAgentConverter(api_key="dummy", model_name="gemini-2.0-flash", max_workers=1)
            
            # Apply post-processing
            deduplicated = converter._deduplicate_form_field_names(form_fields)
            split_groups = converter._split_multipage_radio_groups(deduplicated)
            enriched = converter._enrich_form_fields_with_text(split_groups, {})  # Empty text dict for standalone
            
            return JSONResponse({
                "status": "success",
                "form_fields": enriched,
                "summary": {
                    "total_fields": len(enriched),
                    "deduplication_applied": any(f.get("new_name") != f.get("name") for f in enriched),
                    "multipage_splits": converter._count_multipage_radio_split_groups(enriched)
                }
            })
        except Exception as e:
            logger.error(f"Error in deduplicate-fields: {e}", exc_info=True)
            return JSONResponse({"detail": str(e)}, status_code=500)

    @app.post("/v1/agent/extract-form-fields")
    async def extract_form_fields(file: UploadFile = File(...)):
        """Extract form fields from a PDF without running Gemini tagging.
        
        Accepts: PDF file upload
        Returns: List of form fields with type, name, tooltip, and surrounding text
        """
        try:
            if not file.filename.lower().endswith('.pdf'):
                return JSONResponse({"detail": "File must be a PDF"}, status_code=400)
            
            # Save uploaded file temporarily
            import tempfile
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
                content = await file.read()
                tmp.write(content)
                tmp_path = tmp.name
            
            try:
                # Extract form fields
                from opendataloader_pdf.agent import GeminiAgentConverter
                converter = GeminiAgentConverter(api_key="dummy", model_name="gemini-2.0-flash", max_workers=1)
                result = converter.extract_form_fields_only(tmp_path)
                
                return JSONResponse(result)
            finally:
                # Clean up temp file
                import os
                if os.path.exists(tmp_path):
                    try:
                        os.remove(tmp_path)
                    except Exception as e:
                        logger.warning(f"Could not delete temp file {tmp_path}: {e}")
        
        except Exception as e:
            logger.error(f"Error extracting form fields: {e}", exc_info=True)
            return JSONResponse({"detail": str(e)}, status_code=500)

    @app.post("/v1/agent/detect-missing-form-fields")
    async def detect_missing_form_fields(
        file: UploadFile = File(...),
        page_ranges: Optional[str] = Form(default=None),
        api_key: Optional[str] = Form(default=None),
    ):
        """Visually detect missing form fields that should be added before tagging."""
        try:
            if not file.filename.lower().endswith('.pdf'):
                return JSONResponse({"detail": "File must be a PDF"}, status_code=400)

            import tempfile
            import os

            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
                content = await file.read()
                tmp.write(content)
                tmp_path = tmp.name

            try:
                from opendataloader_pdf.agent import GeminiAgentConverter
                converter = GeminiAgentConverter(
                    api_key=api_key or os.environ.get("GEMINI_API_KEY"),
                    model_name="gemini-2.0-flash",
                    max_workers=1,
                )
                page_range_tuple = None
                if page_ranges:
                    start_s, end_s = page_ranges.split("-", 1) if "-" in page_ranges else (page_ranges, page_ranges)
                    page_range_tuple = (max(0, int(start_s) - 1), max(0, int(end_s) - 1))
                result = converter.detect_missing_form_fields(tmp_path, page_range=page_range_tuple)
                return JSONResponse(result)
            finally:
                if os.path.exists(tmp_path):
                    try:
                        os.remove(tmp_path)
                    except Exception as e:
                        logger.warning(f"Could not delete temp file {tmp_path}: {e}")
        except Exception as e:
            logger.error(f"Error detecting missing form fields: {e}", exc_info=True)
            return JSONResponse({"detail": str(e)}, status_code=500)

    @app.post("/v1/agent/add-form-fields")
    async def add_form_fields(
        file: UploadFile = File(...),
        fields_json: str = Form(...),
    ):
        """Add approved detected form fields to a PDF and return the modified PDF."""
        try:
            if not file.filename.lower().endswith('.pdf'):
                return JSONResponse({"detail": "File must be a PDF"}, status_code=400)

            import tempfile
            import os
            import json

            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_input:
                content = await file.read()
                tmp_input.write(content)
                tmp_input_path = tmp_input.name
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_output:
                tmp_output_path = tmp_output.name

            try:
                provided = json.loads(fields_json)
                form_fields = provided.get("form_fields", provided) if isinstance(provided, dict) else provided
                if not isinstance(form_fields, list):
                    return JSONResponse({"detail": "fields_json must contain a form_fields array"}, status_code=400)

                from opendataloader_pdf.agent import GeminiAgentConverter
                converter = GeminiAgentConverter(api_key="dummy", model_name="gemini-2.0-flash", max_workers=1)
                result = converter.add_form_fields_to_pdf(tmp_input_path, form_fields, tmp_output_path)

                with open(tmp_output_path, 'rb') as f:
                    pdf_content = f.read()

                output_filename = file.filename.replace('.pdf', '_with_fields.pdf')
                return StreamingResponse(
                    iter([pdf_content]),
                    media_type="application/pdf",
                    headers={
                        "Content-Disposition": f'attachment; filename="{output_filename}"',
                        "X-Fields-Added": str(result.get("fields_added", 0)),
                        "X-Fields-Skipped": str(result.get("fields_skipped", 0)),
                    },
                )
            finally:
                for path in [tmp_input_path, tmp_output_path]:
                    if os.path.exists(path):
                        try:
                            os.remove(path)
                        except Exception as e:
                            logger.warning(f"Could not delete temp file {path}: {e}")
        except Exception as e:
            logger.error(f"Error adding form fields: {e}", exc_info=True)
            return JSONResponse({"detail": str(e)}, status_code=500)

    @app.post("/v1/agent/apply-and-save-fields")
    async def apply_and_save_fields(
        file: UploadFile = File(...),
        enriched_json: Optional[str] = Form(default=None)
    ):
        """Extract form fields from PDF, apply enrichment/deduplication, and save as new PDF.
        
        Accepts: 
            - file: PDF file upload
            - enriched_json: Optional pre-computed enriched fields JSON string
        
        Returns: 
            - Modified PDF file for download
        """
        try:
            if not file.filename.lower().endswith('.pdf'):
                return JSONResponse({"detail": "File must be a PDF"}, status_code=400)
            
            # Save uploaded file temporarily
            import tempfile
            import os
            
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_input:
                content = await file.read()
                tmp_input.write(content)
                tmp_input_path = tmp_input.name
            
            # Create output temp file path
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_output:
                tmp_output_path = tmp_output.name
            
            try:
                from opendataloader_pdf.agent import GeminiAgentConverter
                converter = GeminiAgentConverter(api_key="dummy", model_name="gemini-2.0-flash", max_workers=1)
                
                # Extract form fields
                result = converter.extract_form_fields_only(tmp_input_path)
                enriched_fields = result["form_fields"]
                
                # If enriched_json was provided, use that instead
                if enriched_json:
                    try:
                        import json
                        provided = json.loads(enriched_json)
                        if isinstance(provided, dict) and "form_fields" in provided:
                            enriched_fields = provided["form_fields"]
                        elif isinstance(provided, list):
                            enriched_fields = provided
                    except Exception as e:
                        logger.warning(f"Could not parse provided enriched_json: {e}, using extracted fields")
                
                # Apply enriched fields to PDF and save
                update_result = converter.update_pdf_with_enriched_fields(
                    tmp_input_path, 
                    enriched_fields, 
                    tmp_output_path
                )
                
                # Read the modified PDF for response
                with open(tmp_output_path, 'rb') as f:
                    pdf_content = f.read()
                
                # Return the modified PDF as downloadable file
                original_filename = file.filename
                output_filename = original_filename.replace('.pdf', '_updated.pdf')
                
                return StreamingResponse(
                    iter([pdf_content]),
                    media_type="application/pdf",
                    headers={"Content-Disposition": f'attachment; filename="{output_filename}"'}
                )
            finally:
                # Clean up temp files
                for path in [tmp_input_path, tmp_output_path]:
                    if os.path.exists(path):
                        try:
                            os.remove(path)
                        except Exception as e:
                            logger.warning(f"Could not delete temp file {path}: {e}")
        
        except Exception as e:
            logger.error(f"Error applying and saving fields: {e}", exc_info=True)
            return JSONResponse({"detail": str(e)}, status_code=500)

    # Semantic Tag Conversion Endpoints
    @app.post("/v1/agent/extract-tags")
    async def extract_tags(file: UploadFile = File(...)):
        """Extract all tags from PDF for semantic conversion."""
        try:
            if not file.filename.lower().endswith('.pdf'):
                return JSONResponse({"detail": "File must be a PDF"}, status_code=400)
            
            import tempfile
            import os
            
            # Save uploaded file temporarily
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_input:
                content = await file.read()
                tmp_input.write(content)
                tmp_input_path = tmp_input.name
            
            try:
                from opendataloader_pdf.agent import GeminiAgentConverter
                converter = GeminiAgentConverter(api_key="dummy", model_name="gemini-2.0-flash", max_workers=1)
                
                # Extract tags
                result = converter.extract_tags_from_pdf(tmp_input_path)
                
                return JSONResponse(result)
            finally:
                if os.path.exists(tmp_input_path):
                    try:
                        os.remove(tmp_input_path)
                    except Exception as e:
                        logger.warning(f"Could not delete temp file: {e}")
        
        except Exception as e:
            logger.error(f"Error extracting tags: {e}", exc_info=True)
            return JSONResponse({"detail": str(e)}, status_code=500)

    @app.post("/v1/agent/suggest-tags")
    async def suggest_tags(tags_data: dict):
        """Suggest semantic tags based on content analysis."""
        try:
            tags_with_content = tags_data.get("tags", [])
            
            from opendataloader_pdf.agent import GeminiAgentConverter
            converter = GeminiAgentConverter(api_key="dummy", model_name="gemini-2.0-flash", max_workers=1)
            
            # Suggest semantic tags
            result = converter.suggest_semantic_tags(tags_with_content)
            
            return JSONResponse(result)
        
        except Exception as e:
            logger.error(f"Error suggesting tags: {e}", exc_info=True)
            return JSONResponse({"detail": str(e)}, status_code=500)

    @app.post("/v1/agent/apply-tags")
    async def apply_tags(
        file: UploadFile = File(...),
        tag_mappings: str = Form(...),
        restructure_document: str = Form("false"),
    ):
        """Apply semantic tag mappings to PDF."""
        try:
            if not file.filename.lower().endswith('.pdf'):
                return JSONResponse({"detail": "File must be a PDF"}, status_code=400)
            
            import tempfile
            import os
            import json
            
            # Parse tag mappings
            mappings = json.loads(tag_mappings)
            
            # Save uploaded file temporarily
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_input:
                content = await file.read()
                tmp_input.write(content)
                tmp_input_path = tmp_input.name
            
            # Create output temp file path
            with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_output:
                tmp_output_path = tmp_output.name
            
            try:
                from opendataloader_pdf.agent import GeminiAgentConverter
                converter = GeminiAgentConverter(api_key="dummy", model_name="gemini-2.0-flash", max_workers=1)
                
                # Apply tag mappings
                result = converter.apply_semantic_tags(
                    tmp_input_path,
                    mappings,
                    tmp_output_path,
                    restructure_document=restructure_document.lower() in {"1", "true", "yes", "on"},
                )
                
                # Read the modified PDF for response
                with open(tmp_output_path, 'rb') as f:
                    pdf_content = f.read()
                
                # Return the modified PDF as downloadable file
                original_filename = file.filename
                output_filename = original_filename.replace('.pdf', '_tagged.pdf')
                
                return StreamingResponse(
                    iter([pdf_content]),
                    media_type="application/pdf",
                    headers={
                        "Content-Disposition": f'attachment; filename="{output_filename}"',
                        "X-Applied-Count": str(result.get("applied_count", 0)),
                        "X-Mapping-Count": str(len(mappings)),
                        "X-Document-Structured": str(result.get("document_structured", False)).lower(),
                        "X-Page-Containers": str(result.get("page_containers", 0)),
                        "X-Form-Fields-Tagged": str(result.get("form_fields_tagged", 0)),
                        "X-Rejected-Mapping-Count": str(len(result.get("rejected_mappings", {}))),
                    }
                )
            finally:
                # Clean up temp files
                for path in [tmp_input_path, tmp_output_path]:
                    if os.path.exists(path):
                        try:
                            os.remove(path)
                        except Exception as e:
                            logger.warning(f"Could not delete temp file {path}: {e}")
        
        except Exception as e:
            logger.error(f"Error applying tags: {e}", exc_info=True)
            return JSONResponse({"detail": str(e)}, status_code=500)

    # Standard endpoints
    @app.get("/health")
    @app.get("/docling/health")
    @app.get("/docling/picture/health")
    def health():
        """Health check endpoint."""
        return {"status": "ok"}

    @app.post("/v1/convert/file")
    async def convert_file(
        files: UploadFile = File(...),
        page_ranges: Optional[str] = Form(default=None),
    ):
        """Convert PDF file to JSON (DoclingDocument format)."""
        conv = get_gemini_converter() if use_gemini_agent else get_docling_converter()
        return await _process_conversion(conv, files, page_ranges)

    @app.post("/gemini/v1/convert/file")
    async def convert_file_gemini(
        files: UploadFile = File(...),
        page_ranges: Optional[str] = Form(default=None),
    ):
        """Convert PDF file to JSON using Gemini Visual AI Agent."""
        conv = get_gemini_converter()
        return await _process_conversion(conv, files, page_ranges)

    @app.post("/docling/v1/convert/file")
    async def convert_file_docling(
        files: UploadFile = File(...),
        page_ranges: Optional[str] = Form(default=None),
    ):
        """Convert PDF file to JSON using Docling Fast Layout Engine."""
        conv = get_docling_converter()
        return await _process_conversion(conv, files, page_ranges)

    @app.post("/docling/picture/v1/convert/file")
    async def convert_file_docling_picture(
        files: UploadFile = File(...),
        page_ranges: Optional[str] = Form(default=None),
    ):
        """Convert PDF file to JSON using Docling with Picture Descriptions enabled."""
        _ensure_profile_converters()
        conv = profile_converters["picture"]
        
        file_bytes = await files.read()
        import io
        files = UploadFile(filename=files.filename, file=io.BytesIO(file_bytes))
        
        res = await _process_conversion(conv, files, page_ranges)
        
        if res.status_code == 200:
            import json
            import fitz
            import base64
            import requests
            
            body = json.loads(res.body.decode('utf-8'))
            json_content = body.get("document", {}).get("json_content", {})
            pictures = json_content.get("pictures", [])
            
            if pictures:
                try:
                    doc = fitz.open("pdf", file_bytes)
                    from opendataloader_pdf.agent import GeminiAgentConverter
                    agent = get_gemini_converter()
                    
                    for pic in pictures:
                        prov = pic.get("prov", [])
                        if not prov:
                            continue
                        
                        bbox = prov[0].get("bbox", {})
                        if not bbox:
                            continue
                            
                        page_no = prov[0].get("page_no", 1) - 1
                        if page_no < 0 or page_no >= len(doc):
                            continue
                            
                        page = doc[page_no]
                        page_h = page.rect.height
                        
                        # Docling coord_origin is usually BOTTOMLEFT, but sometimes it is TOPLEFT
                        origin = bbox.get("coord_origin", "BOTTOMLEFT")
                        l, t, r, b = bbox["l"], bbox["t"], bbox["r"], bbox["b"]
                        
                        if origin == "BOTTOMLEFT":
                            t_fitz = page_h - t
                            b_fitz = page_h - b
                        else:
                            t_fitz = t
                            b_fitz = b
                            
                        rect = fitz.Rect(min(l, r), min(t_fitz, b_fitz), max(l, r), max(t_fitz, b_fitz))
                        pix = page.get_pixmap(clip=rect, dpi=150)
                        img_bytes = pix.tobytes("png")
                        
                        b64 = base64.b64encode(img_bytes).decode("utf-8")
                        
                        payload = {
                            "contents": [{
                                "parts": [
                                    {"text": picture_description_prompt or "Describe this image for a visually impaired user. Be extremely detailed. Only output the description text."},
                                    {"inlineData": {"mimeType": "image/png", "data": b64}}
                                ]
                            }]
                        }
                        
                        try:
                            gem_res = agent._call_gemini_api_with_retry(payload)
                            text = gem_res.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0].get("text", "").strip()
                            if text:
                                pic["annotations"] = [{"kind": "description", "text": text}]
                                logger.info(f"Gemini successfully described picture on page {page_no + 1}")
                        except Exception as e:
                            logger.error(f"Gemini description failed: {e}")
                            
                    doc.close()
                    # Re-encode body
                    res = JSONResponse(body)
                except Exception as e:
                    logger.error(f"Error enriching docling pictures with Gemini: {e}")
                    
        return res

    def _ensure_profile_converters():
        """Lazily initialize profile converters on first use."""
        if profile_converters:
            return
        profiles = {
            "base": dict(enrich_formula=False, enrich_picture_description=False),
            "picture": dict(enrich_formula=False, enrich_picture_description=True),
            "formula": dict(enrich_formula=True, enrich_picture_description=False),
        }
        for name, opts in profiles.items():
            logger.info(f"Initializing profile converter: {name} ({opts})")
            t0 = time.perf_counter()
            profile_converters[name] = create_converter(
                force_full_page_ocr=force_ocr,
                disable_ocr=disable_ocr,
                ocr_engine=ocr_engine,
                psm=psm,
                ocr_lang=ocr_lang,
                picture_description_prompt=picture_description_prompt,
                device=device,
                **opts,
            )
            logger.info(f"  {name} initialized in {time.perf_counter() - t0:.2f}s")

    @app.post("/v1/profile/file")
    async def profile_file(
        files: UploadFile = File(...),
    ):
        """Run the same PDF through base / +picture / +picture+formula converters.

        Returns per-profile timings for cost comparison.
        """
        _ensure_profile_converters()

        # Stream upload to temp file
        tmp_path = None
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp_path = tmp.name
            while True:
                chunk = await files.read(UPLOAD_CHUNK_SIZE)
                if not chunk:
                    break
                tmp.write(chunk)

        try:
            results = {}
            for profile_name, conv in profile_converters.items():
                def _run(c=conv):
                    with _convert_lock:
                        t0 = time.perf_counter()
                        res = c.convert(tmp_path)
                        return res, time.perf_counter() - t0

                result, wall_time = await asyncio.to_thread(_run)
                timings = extract_timings(result)

                # Count pictures and formulas
                json_content = result.document.export_to_dict()
                pictures = json_content.get("pictures", [])
                pics_total = len(pictures)
                pics_described = sum(
                    1 for p in pictures
                    if p.get("captions") or p.get("annotations")
                )
                texts = json_content.get("texts", [])
                formulas_total = sum(1 for t in texts if t.get("label") == "formula")
                tables_total = len(json_content.get("tables", []))

                results[profile_name] = {
                    "wall_time_s": round(wall_time, 3),
                    "timings": timings,
                    "pictures": {
                        "total": pics_total,
                        "with_description": pics_described,
                    },
                    "formulas": formulas_total,
                    "tables": tables_total,
                }

            return JSONResponse({"status": "success", "profiles": results})

        except Exception as e:
            logger.error(f"Profile failed: {e}\n{traceback.format_exc()}")
            return JSONResponse(
                {"status": "failure", "errors": ["Internal server error"]},
                status_code=500,
            )
        finally:
            if tmp_path and os.path.exists(tmp_path):
                os.unlink(tmp_path)

    return app


def main():
    """Run the server."""
    _check_dependencies()
    import uvicorn

    parser = argparse.ArgumentParser(description="Docling Fast Server for opendataloader-pdf")
    parser.add_argument(
        "--host",
        default=DEFAULT_HOST,
        help=f"Host to bind to (default: {DEFAULT_HOST})",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help=f"Port to bind to (default: {DEFAULT_PORT})",
    )
    parser.add_argument(
        "--log-level",
        default="info",
        choices=["debug", "info", "warning", "error"],
        help="Log level (default: info)",
    )
    # OCR mode: --force-ocr and --no-ocr are mutually exclusive (opposite intents)
    ocr_mode_group = parser.add_mutually_exclusive_group()
    ocr_mode_group.add_argument(
        "--force-ocr",
        action="store_true",
        help="Force full-page OCR on all pages, even pages with embedded text. "
             "Use for scanned PDFs where embedded text is unreliable. "
             "Mutually exclusive with --no-ocr.",
    )
    ocr_mode_group.add_argument(
        "--no-ocr",
        action="store_true",
        help="Disable OCR entirely. Use when input PDFs already have reliable embedded text — "
             "prevents duplicate text extraction from images (charts, diagrams, screenshots). "
             "Mutually exclusive with --force-ocr.",
    )

    # Engine selection — delegated to docling's factory.
    # Choices are computed at parse time; the module-level _OCR_ENGINE_DENYLIST
    # filters engines unsuitable for hybrid local mode (single source of truth
    # shared with create_converter and tests).
    try:
        from docling.models.factories import get_ocr_factory as _get_ocr_factory
        _ocr_engine_choices = sorted(
            set(_get_ocr_factory(allow_external_plugins=False).registered_kind)
            - _OCR_ENGINE_DENYLIST
        )
    except ImportError:
        _ocr_engine_choices = ["easyocr"]
    parser.add_argument(
        "--ocr-engine",
        type=str,
        default="easyocr",
        choices=_ocr_engine_choices,
        help=f"OCR engine. Available: {', '.join(_ocr_engine_choices)}. "
             "Use 'auto' for engine auto-selection per page (delegates the choice to docling). "
             "Each engine has its own license, language coverage, and accuracy characteristics; "
             "this server does not validate engine accuracy. "
             "Default: easyocr (preserves prior behavior).",
    )
    parser.add_argument(
        "--psm",
        type=int,
        default=None,
        help="Tesseract Page Segmentation Mode. Applied only when --ocr-engine is "
             "'tesseract' or 'tesserocr'; ignored for other engines. See "
             "`tesseract --help-extra` for valid values.",
    )
    parser.add_argument(
        "--ocr-lang",
        type=str,
        default=None,
        help="OCR languages (comma-separated). Code system depends on --ocr-engine: "
             "EasyOCR uses ISO 639-1 ('ko,en'), Tesseract uses ISO 639-2 ('kor,eng'), "
             "RapidOCR uses 'english,chinese', ocrmac uses BCP-47 ('en-US'). "
             "If omitted, the engine's default languages are used.",
    )
    parser.add_argument(
        "--enrich-formula",
        action="store_true",
        default=False,
        help="Enable formula enrichment model (LaTeX extraction)",
    )
    parser.add_argument(
        "--no-enrich-formula",
        action="store_false",
        dest="enrich_formula",
    )
    parser.add_argument(
        "--enrich-picture-description",
        action="store_true",
        default=False,
        help="Enable picture description model (alt text generation using SmolVLM)",
    )
    parser.add_argument(
        "--no-enrich-picture-description",
        action="store_false",
        dest="enrich_picture_description",
    )
    parser.add_argument(
        "--picture-description-prompt",
        type=str,
        default=None,
        help="Custom prompt for picture description. If unset or blank/whitespace-only, uses docling's default prompt.",
    )
    parser.add_argument(
        "--max-file-size",
        type=_non_negative_int,
        default=MAX_FILE_SIZE,
        help="Maximum upload file size in MB. 0 means no limit (default: 0).",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        choices=["auto", "cpu", "cuda", "mps", "xpu"],
        help="Accelerator device for model inference: auto (default), cpu, cuda, mps (Apple Silicon), xpu (Intel GPU).",
    )
    parser.add_argument(
        "--use-gemini-agent",
        action="store_true",
        default=False,
        help="Use Gemini multimodal agent for visual layout tagging instead of Docling.",
    )
    parser.add_argument(
        "--gemini-model",
        type=str,
        default="gemini-2.0-flash",
        help="Gemini model name to use for the visual tagger agent. Default: gemini-2.0-flash.",
    )
    args = parser.parse_args()

    # Parse ocr_lang
    ocr_lang = None
    if args.ocr_lang:
        ocr_lang = [lang.strip() for lang in args.ocr_lang.split(",") if lang.strip()]

    # Warn when --no-ocr makes other OCR flags inert. We let it through (rather
    # than failing) because the combination is unambiguous — OCR is off — but
    # silently dropping user-supplied flags is unfriendly.
    if args.no_ocr:
        # argparse cannot distinguish explicit `--ocr-engine easyocr` from the
        # implicit default; peek at argv so an explicitly-typed default value
        # is still treated as a user-supplied (inert) flag and reported.
        argv = sys.argv[1:]
        ocr_engine_explicit = any(
            t == "--ocr-engine" or t.startswith("--ocr-engine=") for t in argv
        )
        ignored = []
        if ocr_engine_explicit:
            ignored.append(f"--ocr-engine {args.ocr_engine}")
        if ocr_lang:
            ignored.append(f"--ocr-lang {args.ocr_lang}")
        if args.psm is not None:
            ignored.append(f"--psm {args.psm}")
        if ignored:
            logger.warning(
                "OCR is disabled (--no-ocr); the following flag(s) will have no "
                "effect: %s",
                ", ".join(ignored),
            )

    # Probe engine availability at startup (only when OCR is on). A missing
    # `tesseract` binary or Python package surfaces here as a clear, actionable
    # error rather than as a deferred runtime exception during the first request.
    if not args.no_ocr and not args.use_gemini_agent:
        ok, err = _check_ocr_engine_available(args.ocr_engine)
        if not ok:
            logger.error(err)
            sys.exit(2)

    # Build enrichment log message
    enrichments = []
    if args.enrich_formula:
        enrichments.append("formula")
    if args.enrich_picture_description:
        enrichments.append("picture-description")

    # Log accelerator detection
    try:
        import torch
        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            cuda_version = torch.version.cuda
            logger.info(f"Accelerator: CUDA — {gpu_name} (CUDA {cuda_version})")
        elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            logger.info("Accelerator: MPS (Apple Silicon)")
        elif hasattr(torch, "xpu") and torch.xpu.is_available():
            logger.info("Accelerator: XPU (Intel GPU)")
        else:
            logger.info("Accelerator: CPU (no GPU detected)")
    except ImportError:
        logger.info("Accelerator: CPU (PyTorch not installed)")
    if args.device != "auto":
        logger.info(f"Device override: --device {args.device}")

    # Convert MB to bytes (0 stays 0 = unlimited)
    max_file_size_bytes = args.max_file_size * 1024 * 1024 if args.max_file_size > 0 else 0

    if args.use_gemini_agent:
        logger.info(f"Starting Gemini Agent Tagging Server on http://{args.host}:{args.port}")
    else:
        logger.info(f"Starting Docling Fast Server on http://{args.host}:{args.port}")
        psm_str = f", psm={args.psm}" if args.psm is not None else ""
        logger.info(
            f"OCR settings: do_ocr={not args.no_ocr}, ocr_engine={args.ocr_engine}, "
            f"force_ocr={args.force_ocr}, lang={ocr_lang or 'default'}{psm_str}"
        )
    if max_file_size_bytes > 0:
        logger.info(f"Max file size: {args.max_file_size}MB")
    else:
        logger.info("Max file size: unlimited")
    if enrichments and not args.use_gemini_agent:
        logger.info(f"Enrichments enabled: {', '.join(enrichments)}")

    app = create_app(
        force_ocr=args.force_ocr,
        disable_ocr=args.no_ocr,
        ocr_engine=args.ocr_engine,
        psm=args.psm,
        ocr_lang=ocr_lang,
        enrich_formula=args.enrich_formula,
        enrich_picture_description=args.enrich_picture_description,
        picture_description_prompt=args.picture_description_prompt,
        max_file_size=max_file_size_bytes,
        device=args.device,
        use_gemini_agent=args.use_gemini_agent,
        gemini_model=args.gemini_model,
    )
    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_level=args.log_level,
        loop=_get_loop_setting(),
    )


if __name__ == "__main__":
    main()
