import json
import os
import tempfile
from unittest.mock import MagicMock, patch

import fitz
import pikepdf
import pytest
from opendataloader_pdf.agent import GeminiAgentConverter


@pytest.fixture
def sample_pdf():
    # Create a simple 1-page PDF using pikepdf
    pdf = pikepdf.Pdf.new()
    page = pdf.add_blank_page(page_size=(612, 792))  # standard Letter size

    # Create a form field widget
    widget_dict = pikepdf.Dictionary(
        Subtype=pikepdf.Name("/Widget"),
        FT=pikepdf.Name("/Tx"),
        T=pikepdf.String("TextField1"),
        Rect=[50, 100, 150, 120],  # [left, bottom, right, top]
    )
    # Add annotation list
    page.Annots = pdf.make_indirect([widget_dict])

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        pdf_path = f.name
    pdf.save(pdf_path)
    pdf.close()

    yield pdf_path

    # Clean up
    if os.path.exists(pdf_path):
        try:
            os.unlink(pdf_path)
        except OSError:
            pass


def test_closest_widget_matching():
    widgets = [
        {"index": 0, "bbox": [100.0, 100.0, 120.0, 150.0], "name": "test1", "tooltip": ""},
        {"index": 1, "bbox": [500.0, 500.0, 520.0, 550.0], "name": "test2", "tooltip": ""},
    ]
    converter = GeminiAgentConverter(api_key="mock")

    # Exact match
    match = converter._find_closest_widget([100.0, 100.0, 120.0, 150.0], widgets)
    assert match is not None
    assert match["index"] == 0

    # Close match (within tolerance)
    match_close = converter._find_closest_widget([102.0, 98.0, 118.0, 152.0], widgets)
    assert match_close is not None
    assert match_close["index"] == 0

    # Out of tolerance
    match_far = converter._find_closest_widget([300.0, 300.0, 320.0, 350.0], widgets)
    assert match_far is None


@patch("requests.post")
def test_gemini_agent_converter(mock_post, sample_pdf):
    # Mock the response from Gemini API
    mock_response = MagicMock()
    mock_response.status_code = 200

    gemini_output = {
        "elements": [
            {"type": "heading", "bbox": [50, 50, 80, 200], "text": "Introduction", "heading_level": 1},
            {
                "type": "paragraph",
                "bbox": [100, 50, 150, 500],
                "text": "This is a sample document for testing the PDF Tagger Agent.",
            },
            {
                "type": "figure",
                "bbox": [200, 50, 400, 400],
                "text": "Chart showing layout metrics",
                "alt_text": "Alt text generated by visual tagger",
                "is_decorative": False,
            },
        ],
        "form_fields": [
            {
                # Page height is 792.
                # PDF box: [50, 100, 150, 120] -> l=50, b=100, r=150, t=120
                # Normalized:
                # ymin = (792 - 120)/792 * 1000 = 848.48
                # ymax = (792 - 100)/792 * 1000 = 873.73
                # xmin = 50/612 * 1000 = 81.69
                # xmax = 150/612 * 1000 = 245.09
                # We round to [848.5, 81.7, 873.7, 245.1]
                "bbox": [848.5, 81.7, 873.7, 245.1],
                "name": "user_first_name",
                "tooltip": "Enter your first name",
            }
        ],
    }

    mock_response.json.return_value = {
        "candidates": [{"content": {"parts": [{"text": json.dumps(gemini_output)}]}}]
    }
    mock_post.return_value = mock_response

    converter = GeminiAgentConverter(api_key="mock_key")
    result = converter.convert(sample_pdf)

    # Assertions
    assert result.status == "success"
    assert result.input.page_count == 1

    # Verify JSON output structure matches Docling structure
    data = result.document.export_to_dict()
    assert "texts" in data
    assert "pictures" in data

    # Verify headings mapping
    headings = [t for t in data["texts"] if t["label"] == "section_header"]
    assert len(headings) == 1
    assert headings[0]["text"] == "Introduction"
    assert headings[0]["meta"]["level"] == 1

    # Verify paragraphs mapping
    paras = [t for t in data["texts"] if t["label"] == "text"]
    assert len(paras) == 1
    assert paras[0]["text"] == "This is a sample document for testing the PDF Tagger Agent."

    # Verify picture mapping
    assert len(data["pictures"]) == 1
    assert data["pictures"][0]["annotations"][0]["text"] == "Alt text generated by visual tagger"

    # Verify pikepdf modified fields
    modified_pdf = pikepdf.Pdf.open(converter.temp_pdf_path)
    annot = modified_pdf.pages[0].Annots[0]

    # Assert updated name and tooltip
    assert str(annot.get("/T")) == "user_first_name"
    assert str(annot.get("/TU")) == "Enter your first name"

    modified_pdf.close()

    # Clean up temp modified PDF
    if os.path.exists(converter.temp_pdf_path):
        os.unlink(converter.temp_pdf_path)
